version: '3'
services:
     
  pio:
    image: 933782373565.dkr.ecr.eu-west-1.amazonaws.com/pio:pio-latest
    ports:
      - 7070:7070
    environment: 
      - "ES_HOST=vpc-prediction-io-mlilctsisxnuweu5pu3qd36vny.eu-west-1.es.amazonaws.com"
      - "ES_PORT=443"
      - "ES_SCHEME=https"
      
      - "HBASE_HOST=pio-hbase.internal.welt.de"
      - "HBASE_PORT=8085"
      
      - "HDFS_HOST=pio-hbase.internal.welt.de"
      - "HDFS_PORT=9000"

  ur:
    image: 933782373565.dkr.ecr.eu-west-1.amazonaws.com/pio:ur-latest
    ports:
      - 8000:8000
    environment: 
      - "ES_HOST=vpc-prediction-io-mlilctsisxnuweu5pu3qd36vny.eu-west-1.es.amazonaws.com"
      - "ES_PORT=443"
      - "ES_SCHEME=https"
      
      - "HBASE_HOST=pio-hbase.internal.welt.de"
      - "HBASE_PORT=8085"
      
      - "HDFS_HOST=pio-hbase.internal.welt.de"
      - "HDFS_PORT=8020"

      - "RUN_MODE=DEPLOY_ONLY"

    depends_on:
      - pio